{"name": "2. Нельзя создать двух одинаковых курьеров", "status": "failed", "statusDetails": {"message": "AssertionError: Сообщение об ошибке не совпадает\nassert {'code': 409,...уйте другой.'} == {'code': 409,...используется'}\n  \n  Omitting 1 identical items, use -vv to show\n  Differing items:\n  {'message': 'Этот логин уже используется. Попробуйте другой.'} != {'message': 'Этот логин уже используется'}\n  Use -v to get more diff", "trace": "self = <test_01_create_courier_api.TestCourierAPI object at 0x105c08ec0>, create_courier = ({'firstName': 'K3Bh1Eri6p', 'login': 'G2asT6GRIo', 'password': 'upNB4KPTuw'}, {'ok': True})\n\n    @allure.title(\"2. Нельзя создать двух одинаковых курьеров\")\n    @allure.description(\n        \"Проверка, что нельзя создать двух одинаковых курьеров и ответом приходит \"\n        \"код 409 и сообщение об ошибке'Этот логин уже используется'\"\n    )\n    @allure.step(\n        \"Отправляем POST-запрос на создание курьера с ранее сгенерированными данными снова\"\n    )\n    def test_create_duplicate_courier(self, create_courier):\n        courier_data, _ = create_courier\n        response = requests.post(f\"{Url.BASE_URL}/courier\", json=courier_data)\n    \n        assert response.status_code == 409, \"Код ответа не 409 для повторного логина\"\n>       assert (\n            response.json() == expected_responses[\"courier\"][\"duplicate_error\"]\n        ), \"Сообщение об ошибке не совпадает\"\nE       AssertionError: Сообщение об ошибке не совпадает\nE       assert {'code': 409,...уйте другой.'} == {'code': 409,...используется'}\nE         \nE         Omitting 1 identical items, use -vv to show\nE         Differing items:\nE         {'message': 'Этот логин уже используется. Попробуйте другой.'} != {'message': 'Этот логин уже используется'}\nE         Use -v to get more diff\n\nAPI-tests/test_01_create_courier_api.py:41: AssertionError"}, "description": "Проверка, что нельзя создать двух одинаковых курьеров и ответом приходит код 409 и сообщение об ошибке'Этот логин уже используется'", "steps": [{"name": "Отправляем POST-запрос на создание курьера с ранее сгенерированными данными снова", "status": "failed", "statusDetails": {"message": "AssertionError: Сообщение об ошибке не совпадает\nassert {'code': 409,...уйте другой.'} == {'code': 409,...используется'}\n  \n  Omitting 1 identical items, use -vv to show\n  Differing items:\n  {'message': 'Этот логин уже используется. Попробуйте другой.'} != {'message': 'Этот логин уже используется'}\n  Use -v to get more diff\n", "trace": "  File \"/Users/vladvihrov/PycharmProjects/YAProjectSprint_7/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/vladvihrov/PycharmProjects/YAProjectSprint_7/API-tests/test_01_create_courier_api.py\", line 41, in test_create_duplicate_courier\n    assert (\n"}, "parameters": [{"name": "create_courier", "value": "({'login': 'G2asT6GRIo', 'password': 'upNB4KPTuw', 'firstName': 'K3Bh1Eri6p'}, {'ok': True})"}], "start": 1725407268828, "stop": 1725407269209}], "start": 1725407268828, "stop": 1725407269211, "uuid": "a2edefe0-05a5-417d-8eb6-5abbf1ffedcd", "historyId": "9e3c9f845e2802556f945ab6fd8ecc74", "testCaseId": "9e3c9f845e2802556f945ab6fd8ecc74", "fullName": "API-tests.test_01_create_courier_api.TestCourierAPI#test_create_duplicate_courier", "labels": [{"name": "suite", "value": "1. Создание курьера"}, {"name": "story", "value": "Тестирование функционала создания курьера"}, {"name": "tag", "value": "@pytest.mark.usefixtures('create_courier')"}, {"name": "parentSuite", "value": "API-tests"}, {"name": "subSuite", "value": "TestCourierAPI"}, {"name": "host", "value": "MacBook-Pro-Vlad.local"}, {"name": "thread", "value": "27095-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API-tests.test_01_create_courier_api"}]}