{"name": "4. Если авторизоваться под несуществующим пользователем, запрос возвращает ошибку", "status": "passed", "description": "Проверка, что система вернёт ошибку при попытке авторизации под несуществующим пользователем", "steps": [{"name": "Отправляем POST-запрос на авторизацию курьера с логином и паролем, которые не существуют", "status": "passed", "start": 1725407333808, "stop": 1725407334129}], "start": 1725407333807, "stop": 1725407334131, "uuid": "1eb5e994-9299-4937-82cd-a61cb2481657", "historyId": "b1286d7af162e8a596f5457e79a1ecb4", "testCaseId": "b1286d7af162e8a596f5457e79a1ecb4", "fullName": "API-tests.test_02_courier_login_api.TestCourierLoginAPI#test_login_nonexistent_user", "labels": [{"name": "suite", "value": "2. Логин курьера"}, {"name": "story", "value": "Тестирование авторизации курьера"}, {"name": "tag", "value": "@pytest.mark.usefixtures('courier_for_login')"}, {"name": "parentSuite", "value": "API-tests"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "MacBook-Pro-Vlad.local"}, {"name": "thread", "value": "27095-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API-tests.test_02_courier_login_api"}]}